name: Java CI/CD Pipeline to Tomcat

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure Maven is installed
        run: |
          if ! command -v mvn &> /dev/null; then
            sudo dnf install -y maven
          fi
          mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: target/*.war

      - name: SonarQube Analysis
        env:
         SONAR_HOST: ${{ secrets.SONAR_HOST }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
           mvn -U verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar \
            -Dsonar.projectKey=Hotstar \
            -Dsonar.projectName=Hotstar \
            -Dsonar.host.url=$SONAR_HOST \
            -Dsonar.login=$SONAR_TOKEN


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Deploy to Tomcat
        run: |
          WAR_FILE=$(ls *.war)
          curl --upload-file "$WAR_FILE" \
            "http://${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}@${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"

      - name: Verify deployment
        run: curl -I http://${{ secrets.TOMCAT_HOST }}/myapp
